### PR TITLE
Add .gitlab-ci.yml

### PR DESCRIPTION
**Pull request by fepitre**

### CODE REVIEW

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
PipelineRetry

**Comment by marmarek** [comment]
@fepitre this doesn't work, missing on the whitelist?

**Comment by fepitre** [comment]
Normally there is no more whitelist

**Comment by fepitre** [comment]
enabled for the app?

**Comment by fepitre** [comment]
PipelineRetry

**Review by marmarek — APPROVED** [review]

**Pull request merged**
